"""Patient-facing lab summary PDF generation.

Professional, deterministic, server-rendered. Uses reportlab to produce a
paginated summary with severity coloring. Avoids the browser print flow.
"""

from __future__ import annotations

from collections.abc import Mapping
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

_BRAND_PINK = colors.HexColor("#FF1570")
_NAVY = colors.HexColor("#121A33")
_INK_SOFT = colors.HexColor("#5A617A")
_SURFACE = colors.HexColor("#FFF6F8")
_BORDER = colors.HexColor("#E5E9F2")

_SEVERITY_COLOR = {
    "S0": colors.HexColor("#1BA672"),
    "S1": colors.HexColor("#B8860B"),
    "S2": colors.HexColor("#D97706"),
    "S3": colors.HexColor("#DC2626"),
    "S4": colors.HexColor("#991B1B"),
    "SX": _INK_SOFT,
}

_SUPPORT_BANNER_LABEL = {
    "fully_supported": "All key findings supported",
    "partially_supported": "Partially supported",
    "could_not_assess": "Could not assess",
}


def _make_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "Title": ParagraphStyle(
            "Title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=_NAVY,
            spaceAfter=4,
        ),
        "Subtitle": ParagraphStyle(
            "Subtitle",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=_INK_SOFT,
            spaceAfter=12,
        ),
        "Section": ParagraphStyle(
            "Section",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=_NAVY,
            spaceBefore=10,
            spaceAfter=6,
        ),
        "Body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=_NAVY,
        ),
        "Meta": ParagraphStyle(
            "Meta",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=_INK_SOFT,
        ),
        "Severity": ParagraphStyle(
            "Severity",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.white,
            alignment=1,
        ),
    }


def _severity_cell(severity_chip: str, styles: dict[str, ParagraphStyle]) -> Table:
    color = _SEVERITY_COLOR.get(severity_chip, _INK_SOFT)
    cell = Table(
        [[Paragraph(severity_chip or "—", styles["Severity"])]],
        colWidths=[14 * mm],
        rowHeights=[6 * mm],
    )
    cell.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), color),
                ("ROUNDEDCORNERS", [3, 3, 3, 3]),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return cell


def _header_footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFillColor(_SURFACE)
    canvas.rect(0, A4[1] - 18 * mm, A4[0], 18 * mm, stroke=0, fill=1)
    canvas.setFillColor(_BRAND_PINK)
    canvas.setFont("Helvetica-Bold", 12)
    canvas.drawString(20 * mm, A4[1] - 11 * mm, "Elfie Labs")
    canvas.setFillColor(_INK_SOFT)
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(
        A4[0] - 20 * mm, A4[1] - 11 * mm, "Patient Lab Summary"
    )
    canvas.setFillColor(_INK_SOFT)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(
        20 * mm, 10 * mm, "Generated by Elfie — not a substitute for medical advice."
    )
    canvas.drawRightString(A4[0] - 20 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_patient_pdf_bytes(patient_artifact: Mapping[str, Any]) -> bytes:
    buffer = BytesIO()
    doc = BaseDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=24 * mm,
        bottomMargin=18 * mm,
        title="Elfie Patient Lab Summary",
        author="Elfie Labs Analyzer",
    )
    frame = Frame(
        doc.leftMargin,
        doc.bottomMargin,
        doc.width,
        doc.height,
        id="normal",
        showBoundary=0,
    )
    doc.addPageTemplates(
        [PageTemplate(id="main", frames=frame, onPage=_header_footer)]
    )

    styles = _make_styles()
    story: list[Any] = []

    job_id = str(patient_artifact.get("job_id", "—"))
    banner = str(patient_artifact.get("support_banner", ""))
    overall_severity = str(patient_artifact.get("overall_severity") or "SX")
    nextstep_title = str(patient_artifact.get("nextstep_title") or "")
    nextstep_body = str(patient_artifact.get("nextstep_body") or "")
    flagged = list(patient_artifact.get("flagged_cards") or [])
    reviewed = list(patient_artifact.get("reviewed_not_flagged") or [])

    story.append(Paragraph("Your Lab Summary", styles["Title"]))
    story.append(
        Paragraph(
            f"Report ID: {job_id}  ·  Status: "
            f"{_SUPPORT_BANNER_LABEL.get(banner, banner or '—')}  ·  "
            f"Overall: {overall_severity}",
            styles["Subtitle"],
        )
    )

    if nextstep_title or nextstep_body:
        story.append(Paragraph("Recommended next step", styles["Section"]))
        if nextstep_title:
            story.append(Paragraph(f"<b>{nextstep_title}</b>", styles["Body"]))
        if nextstep_body:
            story.append(Paragraph(nextstep_body, styles["Body"]))

    story.append(Paragraph("Items to review", styles["Section"]))
    if flagged:
        data = [["", "Analyte", "Value", "Finding"]]
        row_styles: list[tuple] = []
        for idx, card in enumerate(flagged, start=1):
            name = str(card.get("analyte_display") or "—")
            value = str(card.get("value") or "")
            unit = str(card.get("unit") or "")
            combined = f"{value} {unit}".strip()
            finding = str(card.get("finding_sentence") or "—")
            chip = str(card.get("severity_chip") or "SX")
            data.append(
                [
                    _severity_cell(chip, styles),
                    Paragraph(name, styles["Body"]),
                    Paragraph(combined, styles["Body"]),
                    Paragraph(finding, styles["Body"]),
                ]
            )
            if idx % 2 == 0:
                row_styles.append(("BACKGROUND", (0, idx), (-1, idx), _SURFACE))
        tbl = Table(
            data,
            colWidths=[18 * mm, 48 * mm, 32 * mm, 72 * mm],
            repeatRows=1,
        )
        tbl.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), _NAVY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 9),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("GRID", (0, 0), (-1, -1), 0.25, _BORDER),
                ]
                + row_styles
            )
        )
        story.append(tbl)
    else:
        story.append(Paragraph("No items flagged for review.", styles["Body"]))

    if reviewed:
        story.append(Spacer(1, 6))
        story.append(Paragraph("Reviewed (within range)", styles["Section"]))
        chunk_size = 3
        rows = [
            [Paragraph(str(name), styles["Meta"]) for name in reviewed[i : i + chunk_size]]
            for i in range(0, len(reviewed), chunk_size)
        ]
        for row in rows:
            while len(row) < chunk_size:
                row.append(Paragraph("", styles["Meta"]))
        tbl = Table(rows, colWidths=[57 * mm] * chunk_size)
        tbl.setStyle(
            TableStyle(
                [
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                    ("BOX", (0, 0), (-1, -1), 0.25, _BORDER),
                    ("INNERGRID", (0, 0), (-1, -1), 0.25, _BORDER),
                ]
            )
        )
        story.append(tbl)

    doc.build(story)
    return buffer.getvalue()
