from __future__ import annotations

import argparse
import json
import sys
import time
from copy import deepcopy
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx
from pydantic import ValidationError

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
BACKEND_DIR = REPO_ROOT / "backend"

if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.schemas.artifact import (  # noqa: E402
    ClinicianArtifactSchema,
    PatientArtifactSchema,
    UnsupportedReason,
)

TERMINAL_JOB_STATUSES = {"completed", "partial", "failed", "dead_lettered"}
DEFAULT_EXPECTATION = {
    "expected_upload_status_codes": [200],
    "allowed_job_statuses": ["completed", "partial", "failed", "dead_lettered"],
    "require_artifacts_on_job_statuses": ["completed", "partial"],
    "require_proof_pack": True,
    "expected_detail_substrings": [],
}

_NOT_ASSESSED_ALLOWED_KEYS = frozenset({"raw_label", "reason"})
_NOT_ASSESSED_HARD_MAX = 1000
_NOT_ASSESSED_REASON_VALUES = {reason.value for reason in UnsupportedReason}


@dataclass
class RunCounters:
    total: int = 0
    passed: int = 0
    passed_with_warnings: int = 0
    failed: int = 0


def _parse_args() -> argparse.Namespace:
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    parser = argparse.ArgumentParser(
        description="Run strict backend API validation against the full /pdfs corpus."
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8000",
        help="Backend base URL.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=REPO_ROOT / "artifacts" / "validation" / "pdf_manifest.json",
        help="Path to the corpus manifest generated by build_pdf_manifest.py.",
    )
    parser.add_argument(
        "--pdf-root",
        type=Path,
        default=None,
        help="Override the PDF root path from manifest.",
    )
    parser.add_argument(
        "--expectations",
        type=Path,
        default=SCRIPT_DIR / "expected_outcomes.example.json",
        help="Optional expectations file for known failure handling.",
    )
    parser.add_argument(
        "--tiers",
        nargs="+",
        default=["easy", "medium", "hard"],
        help="Tiers to run (easy medium hard).",
    )
    parser.add_argument(
        "--files",
        nargs="+",
        default=[],
        help="Optional list of relative PDF paths from the manifest to run.",
    )
    parser.add_argument(
        "--max-files",
        type=int,
        default=0,
        help="Limit number of files for smoke runs. 0 means no limit.",
    )
    parser.add_argument(
        "--request-timeout-seconds",
        type=float,
        default=90.0,
        help="HTTP timeout per request.",
    )
    parser.add_argument(
        "--poll-timeout-seconds",
        type=float,
        default=60.0,
        help="Max wait time for terminal job status.",
    )
    parser.add_argument(
        "--poll-interval-seconds",
        type=float,
        default=1.0,
        help="Polling interval for /api/jobs/{job_id}/status.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT / "artifacts" / "validation" / "runs" / timestamp,
        help="Directory where run reports are written.",
    )
    parser.add_argument(
        "--fail-on-warning",
        action="store_true",
        help="Treat warnings as failures for non-zero exit code.",
    )
    parser.add_argument(
        "--strict-upload-status",
        action="store_true",
        help="Fail on non-200 uploads instead of tolerating 422 processing_failed as warnings.",
    )
    parser.add_argument(
        "--allow-degraded",
        action="store_true",
        help=(
            "Continue even when /api/health/ready is degraded or db/artifact checks are false. "
            "Default behavior is fail-fast before processing files."
        ),
    )
    parser.add_argument(
        "--fail-fast",
        action="store_true",
        help="Stop after the first failed file instead of processing the full selected set.",
    )
    return parser.parse_args()


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_manifest(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(
            f"Manifest not found at {path}. Run scripts/validation/build_pdf_manifest.py first."
        )
    manifest = _load_json(path)
    if "files" not in manifest or not isinstance(manifest["files"], list):
        raise SystemExit(f"Invalid manifest format in {path}: missing 'files' list.")
    return manifest


def _load_expectations(path: Path | None) -> dict[str, Any]:
    if path is None or not path.exists():
        return {"default": deepcopy(DEFAULT_EXPECTATION), "overrides": {}}

    payload = _load_json(path)
    default = deepcopy(DEFAULT_EXPECTATION)
    override_default = payload.get("default")
    if isinstance(override_default, dict):
        default.update(override_default)

    overrides = payload.get("overrides") if isinstance(payload.get("overrides"), dict) else {}
    return {"default": default, "overrides": overrides}


def _expectation_for(relative_path: str, expectations: dict[str, Any]) -> dict[str, Any]:
    merged = deepcopy(expectations["default"])
    override = expectations["overrides"].get(relative_path)
    if isinstance(override, dict):
        merged.update(override)

    merged["expected_upload_status_codes"] = [
        int(code)
        for code in merged.get(
            "expected_upload_status_codes",
            [200],
        )
    ]
    merged["allowed_job_statuses"] = [
        str(status)
        for status in merged.get(
            "allowed_job_statuses",
            DEFAULT_EXPECTATION["allowed_job_statuses"],
        )
    ]
    merged["require_artifacts_on_job_statuses"] = [
        str(status)
        for status in merged.get(
            "require_artifacts_on_job_statuses",
            ["completed", "partial"],
        )
    ]
    merged["require_proof_pack"] = bool(merged.get("require_proof_pack", True))
    merged["expected_detail_substrings"] = [
        str(part) for part in merged.get("expected_detail_substrings", [])
    ]
    return merged


def _select_files(
    manifest: dict[str, Any],
    tiers: set[str],
    max_files: int,
    requested_files: set[str],
) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    for entry in manifest["files"]:
        relative_path = str(entry.get("relative_path", ""))
        if requested_files and relative_path not in requested_files:
            continue

        tier = str(entry.get("tier", ""))
        if tier not in tiers:
            continue
        selected.append(entry)

    selected.sort(key=lambda item: (str(item.get("tier", "")), str(item.get("relative_path", ""))))
    if max_files > 0:
        return selected[:max_files]
    return selected


def _json_or_text(response: httpx.Response) -> Any:
    try:
        return response.json()
    except json.JSONDecodeError:
        return {"raw_text": response.text[:1000]}


def _poll_job_status(
    client: httpx.Client,
    *,
    base_url: str,
    job_id: str,
    timeout_seconds: float,
    interval_seconds: float,
) -> dict[str, Any]:
    start = time.monotonic()
    samples: list[dict[str, Any]] = []
    last_status: str | None = None

    while True:
        elapsed = time.monotonic() - start
        if elapsed > timeout_seconds:
            return {
                "timed_out": True,
                "elapsed_seconds": round(elapsed, 3),
                "last_status": last_status,
                "samples": samples,
            }

        response = client.get(f"{base_url}/api/jobs/{job_id}/status")
        payload = _json_or_text(response)
        sample: dict[str, Any] = {
            "status_code": response.status_code,
            "payload": payload,
            "elapsed_seconds": round(elapsed, 3),
        }
        samples.append(sample)

        if response.status_code == 200 and isinstance(payload, dict):
            status = payload.get("status")
            if isinstance(status, str):
                last_status = status
                if status in TERMINAL_JOB_STATUSES:
                    return {
                        "timed_out": False,
                        "elapsed_seconds": round(elapsed, 3),
                        "last_status": status,
                        "samples": samples,
                    }

        time.sleep(max(interval_seconds, 0.1))


def _schema_validate_artifact(payload: dict[str, Any], schema_type: str) -> tuple[bool, str | None]:
    try:
        if schema_type == "patient":
            PatientArtifactSchema.model_validate(payload)
        elif schema_type == "clinician":
            ClinicianArtifactSchema.model_validate(payload)
        else:
            return False, f"unknown schema type: {schema_type}"
    except ValidationError as exc:
        return False, str(exc)
    return True, None


def _semantic_validate_not_assessed(payload: dict[str, Any], *, artifact_name: str) -> list[str]:
    violations: list[str] = []
    not_assessed = payload.get("not_assessed")

    if not isinstance(not_assessed, list):
        return [f"{artifact_name}_not_assessed_not_list"]

    if len(not_assessed) > _NOT_ASSESSED_HARD_MAX:
        violations.append(
            f"{artifact_name}_not_assessed_hard_limit_exceeded:{len(not_assessed)}"
        )

    findings = payload.get("findings")
    if isinstance(findings, list):
        runtime_limit = len(findings) + (1 if artifact_name == "patient" else 0)
        if len(not_assessed) > runtime_limit:
            violations.append(
                f"{artifact_name}_not_assessed_runtime_limit_exceeded:"
                f"{len(not_assessed)}>{runtime_limit}"
            )

    if artifact_name == "patient":
        support_banner = payload.get("support_banner")
    else:
        support_banner = payload.get("support_coverage")
    if support_banner == "fully_supported" and not_assessed:
        violations.append(f"{artifact_name}_fully_supported_with_not_assessed_entries")

    seen: set[tuple[str, str]] = set()
    for index, item in enumerate(not_assessed):
        if not isinstance(item, dict):
            violations.append(f"{artifact_name}_not_assessed_item_not_object:{index}")
            continue

        if set(item.keys()) != _NOT_ASSESSED_ALLOWED_KEYS:
            violations.append(f"{artifact_name}_not_assessed_item_keys_invalid:{index}")

        raw_label = item.get("raw_label")
        reason = item.get("reason")

        if not isinstance(raw_label, str) or not raw_label.strip():
            violations.append(f"{artifact_name}_not_assessed_raw_label_invalid:{index}")
        if not isinstance(reason, str) or reason not in _NOT_ASSESSED_REASON_VALUES:
            violations.append(f"{artifact_name}_not_assessed_reason_invalid:{index}")

        if isinstance(raw_label, str) and isinstance(reason, str):
            dedupe_key = (raw_label.strip().lower(), reason)
            if dedupe_key in seen:
                violations.append(f"{artifact_name}_not_assessed_duplicate_entry:{index}")
            seen.add(dedupe_key)

    return violations


def _semantic_validate_not_assessed_parity(
    patient_payload: dict[str, Any],
    clinician_payload: dict[str, Any],
) -> list[str]:
    patient_items = patient_payload.get("not_assessed")
    clinician_items = clinician_payload.get("not_assessed")
    if not isinstance(patient_items, list) or not isinstance(clinician_items, list):
        return ["not_assessed_parity_not_evaluable"]

    patient_pairs = {
        (str(item.get("raw_label", "")).strip(), str(item.get("reason", "")).strip())
        for item in patient_items
        if isinstance(item, dict)
    }
    clinician_pairs = {
        (str(item.get("raw_label", "")).strip(), str(item.get("reason", "")).strip())
        for item in clinician_items
        if isinstance(item, dict)
    }

    patient_only_comparable = {
        pair
        for pair in patient_pairs
        if pair[1] == UnsupportedReason.COMPARABLE_HISTORY_UNAVAILABLE.value
    }

    if (patient_pairs - patient_only_comparable) != clinician_pairs:
        return ["not_assessed_patient_clinician_parity_mismatch"]
    return []


def _run_preflight(client: httpx.Client, base_url: str) -> dict[str, Any]:
    results: dict[str, Any] = {}
    for route in ("/api/health", "/api/health/ready", "/api/health/metrics"):
        response = client.get(f"{base_url}{route}")
        results[route] = {
            "status_code": response.status_code,
            "payload": _json_or_text(response),
        }
    return results


def _evaluate_readiness(preflight: dict[str, Any]) -> tuple[list[str], bool | None]:
    issues: list[str] = []
    db_reachable: bool | None = None

    ready_result = preflight.get("/api/health/ready", {})
    ready_status = ready_result.get("status_code")
    if ready_status != 200:
        issues.append(f"ready_endpoint_status:{ready_status}")

    ready_payload = ready_result.get("payload")
    if not isinstance(ready_payload, dict):
        issues.append("ready_payload_not_object")
        return issues, db_reachable

    checks = ready_payload.get("checks")
    if not isinstance(checks, dict):
        issues.append("ready_checks_missing")
        return issues, db_reachable

    maybe_db_reachable = checks.get("db_reachable")
    if isinstance(maybe_db_reachable, bool):
        db_reachable = maybe_db_reachable
        if not maybe_db_reachable:
            issues.append("db_reachable:false")
    else:
        issues.append("db_reachable:missing")

    artifact_store_writable = checks.get("artifact_store_writable")
    if isinstance(artifact_store_writable, bool):
        if not artifact_store_writable:
            issues.append("artifact_store_writable:false")
    else:
        issues.append("artifact_store_writable:missing")

    return issues, db_reachable


def _process_file(
    client: httpx.Client,
    *,
    base_url: str,
    pdf_root: Path,
    entry: dict[str, Any],
    expectation: dict[str, Any],
    db_reachable: bool | None,
    allow_processing_failed_uploads: bool,
    poll_timeout_seconds: float,
    poll_interval_seconds: float,
) -> dict[str, Any]:
    relative_path = str(entry["relative_path"])
    pdf_path = pdf_root / relative_path
    result: dict[str, Any] = {
        "relative_path": relative_path,
        "tier": entry.get("tier"),
        "expectation": expectation,
        "errors": [],
        "warnings": [],
    }

    if not pdf_path.exists():
        result["errors"].append(f"missing_pdf_file:{pdf_path}")
        result["outcome"] = "failed"
        return result

    with pdf_path.open("rb") as handle:
        upload_response = client.post(
            f"{base_url}/api/upload",
            files={"file": (pdf_path.name, handle, "application/pdf")},
        )

    upload_payload = _json_or_text(upload_response)
    result["upload"] = {
        "status_code": upload_response.status_code,
        "payload": upload_payload,
    }

    detail_text = ""
    if isinstance(upload_payload, dict):
        detail_text = str(upload_payload.get("detail", ""))

    tolerated_processing_failed_upload = (
        allow_processing_failed_uploads
        and upload_response.status_code == 422
        and detail_text == "processing_failed"
    )

    if (
        upload_response.status_code not in expectation["expected_upload_status_codes"]
        and not tolerated_processing_failed_upload
    ):
        result["errors"].append(
            "unexpected_upload_status:"
            f"{upload_response.status_code}:expected={expectation['expected_upload_status_codes']}"
        )

    expected_detail_substrings = expectation.get("expected_detail_substrings", [])
    if expected_detail_substrings:
        missing_parts = [
            part for part in expected_detail_substrings if part not in detail_text
        ]
        if missing_parts:
            result["errors"].append(
                "missing_expected_detail_substrings:" + ",".join(missing_parts)
            )

    if upload_response.status_code != 200:
        if tolerated_processing_failed_upload:
            result["warnings"].append("upload_processing_failed")
        if not result["errors"]:
            result["outcome"] = "passed_with_warnings" if result["warnings"] else "passed"
        else:
            result["outcome"] = "failed"
        return result

    if not isinstance(upload_payload, dict):
        result["errors"].append("upload_payload_not_json_object")
        result["outcome"] = "failed"
        return result

    job_id = upload_payload.get("job_id")
    if not isinstance(job_id, str) or not job_id:
        result["errors"].append("missing_job_id_in_upload_payload")
        result["outcome"] = "failed"
        return result

    poll_result = _poll_job_status(
        client,
        base_url=base_url,
        job_id=job_id,
        timeout_seconds=poll_timeout_seconds,
        interval_seconds=poll_interval_seconds,
    )
    result["status_poll"] = poll_result

    final_status = poll_result.get("last_status") or upload_payload.get("status")
    result["final_status"] = final_status

    if poll_result.get("timed_out"):
        result["errors"].append("job_status_poll_timeout")

    if final_status not in expectation["allowed_job_statuses"]:
        result["errors"].append(
            f"unexpected_final_status:{final_status}:expected={expectation['allowed_job_statuses']}"
        )

    job_response = client.get(f"{base_url}/api/jobs/{job_id}")
    job_payload = _json_or_text(job_response)
    result["job"] = {
        "status_code": job_response.status_code,
        "payload": job_payload,
    }
    if job_response.status_code != 200:
        result["errors"].append(f"job_fetch_failed:{job_response.status_code}")

    requires_artifacts = final_status in expectation["require_artifacts_on_job_statuses"]
    if requires_artifacts:
        patient_response = client.get(f"{base_url}/api/artifacts/{job_id}/patient")
        patient_payload = _json_or_text(patient_response)
        patient_check: dict[str, Any] = {
            "status_code": patient_response.status_code,
            "payload": patient_payload,
            "schema_valid": False,
            "schema_error": None,
            "semantic_valid": False,
            "semantic_errors": [],
        }
        if patient_response.status_code == 200 and isinstance(patient_payload, dict):
            schema_valid, schema_error = _schema_validate_artifact(patient_payload, "patient")
            patient_check["schema_valid"] = schema_valid
            patient_check["schema_error"] = schema_error
            if not schema_valid:
                result["errors"].append("patient_schema_validation_failed")
            else:
                semantic_errors = _semantic_validate_not_assessed(
                    patient_payload,
                    artifact_name="patient",
                )
                patient_check["semantic_errors"] = semantic_errors
                patient_check["semantic_valid"] = len(semantic_errors) == 0
                if semantic_errors:
                    for semantic_error in semantic_errors:
                        result["errors"].append(f"patient_semantic_validation_failed:{semantic_error}")
        else:
            result["errors"].append(f"patient_artifact_fetch_failed:{patient_response.status_code}")
        result["patient_artifact"] = patient_check

        clinician_response = client.get(f"{base_url}/api/artifacts/{job_id}/clinician")
        clinician_payload = _json_or_text(clinician_response)
        clinician_check: dict[str, Any] = {
            "status_code": clinician_response.status_code,
            "payload": clinician_payload,
            "schema_valid": False,
            "schema_error": None,
            "semantic_valid": False,
            "semantic_errors": [],
        }
        if clinician_response.status_code == 200 and isinstance(clinician_payload, dict):
            schema_valid, schema_error = _schema_validate_artifact(clinician_payload, "clinician")
            clinician_check["schema_valid"] = schema_valid
            clinician_check["schema_error"] = schema_error
            if not schema_valid:
                result["errors"].append("clinician_schema_validation_failed")
            else:
                semantic_errors = _semantic_validate_not_assessed(
                    clinician_payload,
                    artifact_name="clinician",
                )
                clinician_check["semantic_errors"] = semantic_errors
                clinician_check["semantic_valid"] = len(semantic_errors) == 0
                if semantic_errors:
                    for semantic_error in semantic_errors:
                        result["errors"].append(
                            f"clinician_semantic_validation_failed:{semantic_error}"
                        )
        else:
            result["errors"].append(
                f"clinician_artifact_fetch_failed:{clinician_response.status_code}"
            )
        result["clinician_artifact"] = clinician_check

        if (
            patient_check["schema_valid"]
            and clinician_check["schema_valid"]
            and patient_check["semantic_valid"]
            and clinician_check["semantic_valid"]
        ):
            parity_errors = _semantic_validate_not_assessed_parity(
                patient_payload,
                clinician_payload,
            )
            result["not_assessed_parity_errors"] = parity_errors
            for parity_error in parity_errors:
                result["errors"].append(parity_error)

        if expectation.get("require_proof_pack", True):
            if db_reachable is False:
                result["audit"] = {
                    "status": "skipped",
                    "reason": "db_unreachable_in_preflight",
                }
                result["warnings"].append("job_audit_skipped_db_unreachable")
            else:
                audit_response = client.get(f"{base_url}/api/jobs/{job_id}/audit")
                audit_payload = _json_or_text(audit_response)
                result["audit"] = {
                    "status_code": audit_response.status_code,
                    "payload": audit_payload,
                }
                if audit_response.status_code != 200:
                    result["errors"].append(
                        f"job_audit_fetch_failed:{audit_response.status_code}"
                    )

            proof_response = client.get(f"{base_url}/api/jobs/{job_id}/proof-pack")
            proof_payload = _json_or_text(proof_response)
            result["proof_pack"] = {
                "status_code": proof_response.status_code,
                "payload": proof_payload,
            }
            if proof_response.status_code != 200:
                result["errors"].append(f"proof_pack_fetch_failed:{proof_response.status_code}")
            elif isinstance(proof_payload, dict):
                if proof_payload.get("contract_version") != "benchmark-proof-pack-v1":
                    result["errors"].append("unexpected_proof_pack_contract_version")
                reports = proof_payload.get("reports")
                if not isinstance(reports, dict) or not reports:
                    result["errors"].append("proof_pack_reports_missing")
            else:
                result["errors"].append("proof_pack_payload_not_json_object")

    if final_status in {"failed", "dead_lettered"} and not result["errors"]:
        result["warnings"].append(f"non_success_job_status:{final_status}")

    if result["errors"]:
        result["outcome"] = "failed"
    elif result["warnings"]:
        result["outcome"] = "passed_with_warnings"
    else:
        result["outcome"] = "passed"

    return result


def _render_markdown_summary(
    *,
    report_path: Path,
    run_payload: dict[str, Any],
) -> None:
    lines: list[str] = []
    lines.append("# Backend Corpus Validation Run")
    lines.append("")
    lines.append(f"- Generated at: {run_payload['generated_at']}")
    lines.append(f"- Base URL: {run_payload['base_url']}")
    lines.append(f"- Manifest: {run_payload['manifest_path']}")
    lines.append(f"- Selected files: {run_payload['selected_file_count']}")
    lines.append(f"- Processed files: {run_payload['summary'].get('processed_total', 0)}")
    lines.append(f"- Total files: {run_payload['summary']['total']}")
    lines.append(f"- Passed: {run_payload['summary']['passed']}")
    lines.append(
        f"- Passed with warnings: {run_payload['summary']['passed_with_warnings']}"
    )
    lines.append(f"- Failed: {run_payload['summary']['failed']}")
    readiness_issues = run_payload.get("readiness_issues") or []
    if readiness_issues:
        lines.append(f"- Readiness issues: {', '.join(readiness_issues)}")
    if run_payload.get("aborted"):
        lines.append(f"- Aborted: {run_payload['aborted'].get('reason', 'unknown')}")
    if run_payload.get("stopped_early"):
        lines.append("- Stopped early: true")
    lines.append("")

    lines.append("## Preflight")
    lines.append("")
    preflight = run_payload.get("preflight", {})
    for route, payload in preflight.items():
        lines.append(f"- {route}: HTTP {payload.get('status_code')}")
    lines.append("")

    lines.append("## Failed Files")
    lines.append("")
    failures = [item for item in run_payload["files"] if item["outcome"] == "failed"]
    if not failures:
        lines.append("- None")
    else:
        for item in failures:
            lines.append(f"- {item['relative_path']}: {', '.join(item['errors'])}")
    lines.append("")

    lines.append("## Warning Files")
    lines.append("")
    warnings = [
        item for item in run_payload["files"] if item["outcome"] == "passed_with_warnings"
    ]
    if not warnings:
        lines.append("- None")
    else:
        for item in warnings:
            lines.append(f"- {item['relative_path']}: {', '.join(item['warnings'])}")

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = _parse_args()

    base_url = args.base_url.rstrip("/")
    manifest_path = args.manifest.resolve()
    manifest = _load_manifest(manifest_path)

    expectations = _load_expectations(args.expectations.resolve() if args.expectations else None)

    if args.pdf_root is not None:
        pdf_root = args.pdf_root.resolve()
    else:
        manifest_pdf_root = manifest.get("pdf_root")
        if manifest_pdf_root:
            pdf_root = Path(str(manifest_pdf_root)).resolve()
        else:
            pdf_root = REPO_ROOT / "pdfs"

    tiers = {tier.strip().lower() for tier in args.tiers if tier.strip()}
    requested_files = {value.strip() for value in args.files if value.strip()}
    selected_files = _select_files(
        manifest,
        tiers,
        args.max_files,
        requested_files,
    )

    if requested_files:
        selected_relative_paths = {
            str(item.get("relative_path", "")) for item in selected_files
        }
        missing_files = sorted(requested_files - selected_relative_paths)
        if missing_files:
            raise SystemExit(
                "Requested files were not found in selected manifest/tier set: "
                + ", ".join(missing_files)
            )

    if not selected_files:
        raise SystemExit("No files selected for run. Check --tiers or manifest content.")

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    counters = RunCounters(total=len(selected_files))
    run_payload: dict[str, Any] = {
        "generated_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "base_url": base_url,
        "manifest_path": str(manifest_path),
        "pdf_root": str(pdf_root),
        "selected_tiers": sorted(tiers),
        "selected_file_count": len(selected_files),
        "preflight": {},
        "files": [],
        "summary": {},
    }

    with httpx.Client(timeout=args.request_timeout_seconds) as client:
        run_payload["preflight"] = _run_preflight(client, base_url)
        readiness_issues, db_reachable = _evaluate_readiness(run_payload["preflight"])
        run_payload["readiness_issues"] = readiness_issues

        if readiness_issues and not args.allow_degraded:
            run_payload["aborted"] = {
                "reason": "degraded_stack",
                "details": readiness_issues,
            }
            run_payload["summary"] = {
                "total": 0,
                "processed_total": 0,
                "selected_total": len(selected_files),
                "passed": 0,
                "passed_with_warnings": 0,
                "failed": 0,
            }
            json_report = output_dir / "backend_corpus_validation.json"
            markdown_report = output_dir / "backend_corpus_validation.md"
            json_report.write_text(json.dumps(run_payload, indent=2), encoding="utf-8")
            _render_markdown_summary(report_path=markdown_report, run_payload=run_payload)
            print(
                "Aborting run because stack readiness checks failed. "
                f"Use --allow-degraded to override. Issues: {', '.join(readiness_issues)}"
            )
            print(f"Wrote JSON report: {json_report}")
            print(f"Wrote summary report: {markdown_report}")
            return 3

        for index, entry in enumerate(selected_files, start=1):
            relative_path = str(entry["relative_path"])
            expectation = _expectation_for(relative_path, expectations)
            print(f"[{index}/{len(selected_files)}] Processing {relative_path}")
            file_result = _process_file(
                client,
                base_url=base_url,
                pdf_root=pdf_root,
                entry=entry,
                expectation=expectation,
                db_reachable=db_reachable,
                allow_processing_failed_uploads=not args.strict_upload_status,
                poll_timeout_seconds=args.poll_timeout_seconds,
                poll_interval_seconds=args.poll_interval_seconds,
            )
            run_payload["files"].append(file_result)

            if args.fail_fast and file_result.get("outcome") == "failed":
                run_payload["stopped_early"] = True
                print(
                    "Fail-fast enabled: stopping after first failed file "
                    f"({relative_path})."
                )
                break

    counters.total = len(run_payload["files"])

    for item in run_payload["files"]:
        outcome = item["outcome"]
        if outcome == "passed":
            counters.passed += 1
        elif outcome == "passed_with_warnings":
            counters.passed_with_warnings += 1
        else:
            counters.failed += 1

    run_payload["summary"] = {
        "total": counters.total,
        "processed_total": counters.total,
        "selected_total": len(selected_files),
        "passed": counters.passed,
        "passed_with_warnings": counters.passed_with_warnings,
        "failed": counters.failed,
    }

    json_report = output_dir / "backend_corpus_validation.json"
    markdown_report = output_dir / "backend_corpus_validation.md"
    json_report.write_text(json.dumps(run_payload, indent=2), encoding="utf-8")
    _render_markdown_summary(report_path=markdown_report, run_payload=run_payload)

    print(f"Wrote JSON report: {json_report}")
    print(f"Wrote summary report: {markdown_report}")
    print(
        "Run summary: "
        f"total={counters.total} passed={counters.passed} "
        f"warnings={counters.passed_with_warnings} failed={counters.failed}"
    )

    if counters.failed > 0:
        return 1
    if args.fail_on_warning and counters.passed_with_warnings > 0:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
